version: '3'

services:
  zookeeper:
    build:
      context: ./extra/infra/kafka
    ports:
      - '2181:2181'
    command: /root/kafka_2.13-2.4.0/bin/zookeeper-server-start.sh /root/kafka_2.13-2.4.0/config/zookeeper.properties
  kafka:
    build:
      context: ./extra/infra/kafka
    ports:
      - '9092:9092'
    depends_on:
      - 'zookeeper'
    command: sh -c 'python /root/wait_for_tcp.py zookeeper 2181 60 && cd /root/kafka_2.13-2.4.0/ && sed -i s/localhost/zookeeper/ config/server.properties && echo -e "\nlisteners=PLAINTEXT://kafka:9092" >> config/server.properties && sed -i s/broker.id=0/broker.id=1/ config/server.properties && bin/kafka-server-start.sh config/server.properties'
  python:
    image: python:3
    tty: true
    volumes:
      - ./:/usr/local/app


